### ISSUE TITLE
Warning when using Distributions package

### ISSUE THREAD

**Issue by tkosaka1976** [JuliaStats/Rmath.jl#61]
I got this warning when using HypothsisTests:

┌ Warning: Package Rmath does not have Libdl in its dependencies:
│ - If you have Rmath checked out for development and have
│   added Libdl as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with Rmath
└ Loading Libdl into Rmath from project dependency, future warnings for Rmath are suppressed.

Pkg.resolve() did not solve this warning.
I'm using julia 0.7.0 on macosx 10.13.6.

**Comment by ararslan** [comment]
This is a known issue with packages that use BinaryProvider. Basically, the issue is that the code produced by BinaryProvider which tells the package where to look for the binaries includes a call to Libdl. But since that code is `include`d by the package, it sees Libdl but hasn't explicitly declared a dependency on it. The warning itself is harmless and will be addressed upstream.

**Comment by tkosaka1976** [comment]
I see. I understood.
However, this warning looks like related to the fail of precompile.
Is this a different reasons?
I think a precompile cache is important for package loading speed itself, don't you?

┌ Warning: The call to compilecache failed to create a usable precompiled cache file for Distributions [31c24e10-a181-5473-b8eb-7969acd0382f]
│   exception = Required dependency Rmath [79098fc4-a85e-5d69-aa6a-4863f24498fa] failed to load from a cache file.
└ @ Base loading.jl:963

**Comment by andreasnoack** [comment]
I'm unable to reproduce this. Could you try to update your packages and report if the issue persists?

**Comment by tkosaka1976** [comment]
Thank you for your inform.
I also updated and checked no warning.
